/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5aa0801c-8fb2-4398-9d95-7cc9126bad59",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_AbNfkUDLp",
    "aws_user_pools_web_client_id": "b3gmnsdkord8o6temmuva8ok1",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment_dev",
            "alias": "$LATEST",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "devnlpengineRestfulApi",
            "endpoint": "https://x2pjhxdl3b.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
